### PR TITLE
Fix build with GHC 9.2.1

### LINKED ISSUE #32: Build failure with GHC 9.2.1
```
src/Generic/Random/Internal/BaseCase.hs:191:3: error:
    • Could not deduce (Alternative (IfM y Weighted Proxy))
        arising from the superclasses of an instance declaration
      from the context: (GBCSSum f g z e yf yg, GBCS f z yf e,
                         GBCS g z yg e, y ~ (yf ||? yg))
        bound by the instance declaration
        at src/Generic/Random/Internal/BaseCase.hs:(191,3)-(195,27)
    • In the instance declaration for ‘GBCS (f :+: g) z y e’
    |
191 |   ( GBCSSum f g z e yf yg
    |   ^^^^^^^^^^^^^^^^^^^^^^^...

src/Generic/Random/Internal/BaseCase.hs:239:3: error:
    • Could not deduce (Alternative (IfM y Weighted Proxy))
        arising from the superclasses of an instance declaration
      from the context: (GBCSProduct f g z e yf yg, GBCS f z yf e,
                         GBCS g z yg e, y ~ (yf &&? yg))
        bound by the instance declaration
        at src/Generic/Random/Internal/BaseCase.hs:(239,3)-(243,27)
    • In the instance declaration for ‘GBCS (f :*: g) z y e’
    |
239 |   ( GBCSProduct f g z e yf yg
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build generic-random-1.5.0.0
```

### PR DESCRIPTION
**Pull request by goldfirere**
This adds two logically redundant constraints, but restrictions in GHC (intended to avoid bottom dictionaries) mean that GHC is not clever enough to deduce these.

Really, it was a bug that prior versions of GHC accepted these instances. Happily, this fix is easy enough.

Fix #32.

### CODE REVIEW

**Comment by Lysxia** [comment]
Great! Thanks for looking into this!
